import path from 'path';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { db } from './index';

// SQL migrations generated by drizzle-kit live in backend/drizzle.
// The relative path is the same from src/db (tsx) and dist/db (compiled).
const MIGRATIONS_FOLDER = path.resolve(__dirname, '../../drizzle');

export async function runMigrations() {
  await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
  console.log('[db] migrations applied');
}

if (require.main === module) {
  runMigrations()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('[db] migration failed:', err);
      process.exit(1);
    });
}
